name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4']
        dependencies: ['highest']
        include:
          - php-version: '8.3'
            dependencies: 'lowest'

    name: PHP ${{ matrix.php-version }} - ${{ matrix.dependencies }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json
        coverage: none
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-
          ${{ runner.os }}-php-${{ matrix.php-version }}-
          ${{ runner.os }}-php-

    - name: Install dependencies (highest)
      if: matrix.dependencies == 'highest'
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Install dependencies (lowest)
      if: matrix.dependencies == 'lowest'
      run: composer update --prefer-lowest --prefer-dist --no-progress --no-interaction

    - name: Check PHP syntax
      run: find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected" && exit 1 || exit 0

    - name: Run test suite
      run: composer test

    - name: Run PHP CS Fixer check
      run: composer cs-check
