name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    name: Create Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run tests
      run: composer test

    - name: Run code style check
      run: composer cs-check

    - name: Get tag name
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Generate changelog
      id: changelog
      run: |
        if [ -f CHANGELOG.md ]; then
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          sed -n "/^## \[${{ steps.tag.outputs.tag }}\]/,/^## \[/p" CHANGELOG.md | head -n -1 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "changelog=Release ${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        body: |
          ## Changes in ${{ steps.tag.outputs.tag }}

          ${{ steps.changelog.outputs.changelog }}

          ## Installation

          ```bash
          composer require mellivora/logger-factory:${{ steps.tag.outputs.tag }}
          ```

          ## Requirements

          - PHP 8.3+
          - Monolog ^3.0

          ## Documentation

          - [README](https://github.com/zhouyl/mellivora-logger-factory/blob/master/README.md)
          - [Laravel Integration](https://github.com/zhouyl/mellivora-logger-factory/blob/master/docs/LARAVEL.md)
          - [Testing Guide](https://github.com/zhouyl/mellivora-logger-factory/blob/master/docs/TESTING.md)
        draft: false
        prerelease: ${{ contains(steps.tag.outputs.tag, 'alpha') || contains(steps.tag.outputs.tag, 'beta') || contains(steps.tag.outputs.tag, 'rc') }}
        token: ${{ secrets.GITHUB_TOKEN }}

  packagist:
    needs: release
    runs-on: ubuntu-latest

    name: Update Packagist

    steps:
    - name: Update Packagist
      run: |
        curl -XPOST -H'content-type:application/json' \
          'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
          -d'{"repository":{"url":"https://github.com/zhouyl/mellivora-logger-factory"}}'
      continue-on-error: true
